<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="us-ascii">
    <title> <?php echo $title ?> </title>
    <!-- подключаем файлы стилей -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="/resource/jquery-3.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="http://js.nicedit.com/nicEdit-latest.js"></script>

    <link rel="stylesheet" href="/resource/select2.min.css">
    <script type="text/javascript" src="/resource/select2.min.js"></script>
    <link rel="stylesheet" href="/resource/bootstrap-editable.css">
    <script type="text/javascript" src="/resource/bootstrap-editable.min.js"></script>

    <!-- закончили подключать файлы стилей -->

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Каталог товаров</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/">Главная</a></li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Товары
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/products/addProduct.php">Создать товар</a></li>
                    <li><a href="/products/productList.php">Товары</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Накладные
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/products/addGroupProduct.php">Создать накладную</a></li>
                    <li><a href="/products/consignmentList.php">Накладные</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Клиенты
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/clients/clientList.php">Клиенты</a></li>
                    <li><a href="/clients/addClient.php">Создать клиента</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Касса
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/cashier/incomes.php">Приходы</a></li>
                    <li><a href="/cashier/expenses.php">Расходы</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Настройки
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/setup/changeSetup.php">Изменить</a></li>
                </ul>
            </li>

        </ul>
    </div>
</nav>

<!-- Напоминание о заявке внести товары -->
<script type="text/javascript">
    <?php if(isset($_GET['redirectConfirm'])){
        echo 'var isRedirect = true';
    }else{
        echo 'var isRedirect = false';
    } ?>

    function printNumbersInterval() {
        var timerId = setInterval(function() {

            $.ajax({
                url: '/clients/rememberCommentProduct.php',
                success: function(data) {
                    var response = JSON.parse(data);
                    if(!isRedirect) {
                        if (response.status == 'remember') {
                            if (confirm("В заявку #" + response.data.id + " нужно добавить товары, перейти?") == true) {
                                window.clearInterval(timerId);
                                window.open("/clients/addProductToClient.php?redirectConfirm=1&client=" + response.data.client + "&comment=" + response.data.id)
                            } else {

                            }
                        }
                    }
                }
            });

        }, 60000);
    }

    // вызов
    printNumbersInterval();

</script>

<!-- Напоминание о заказе за Х дней до прихода-->

<script type="text/javascript">
    <?php if(isset($_GET['redirectConfirm'])){
        echo 'var isRedirect = true';
    }else{
        echo 'var isRedirect = false';
    } ?>

    function printNumbersInterval() {
        var timerId = setInterval(function() {

            $.ajax({
                url: '/clients/rememberCommentComeTime.php',
                success: function(data) {
                    var response = JSON.parse(data);
                    if(!isRedirect) {
                        if (response.status == 'remember') {
                            if (confirm("Нужно проверить заказ #" + response.data.id + ", перейти?") == true) {
                                window.clearInterval(timerId);
                                window.open("/clients/clientList.php?redirectConfirm=1&client=" + response.data.client)
                            } else {

                            }
                        }
                    }
                }
            });

        }, 60000);
    }

    // вызов
    printNumbersInterval();

</script>