<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>


<div class="row">


    <div class="col-md-1"></div>

    <div class="col-md-6">

        <!-- Если были заполнены не все поля говорим об этом -->
        <?php if (isset($error)) { ?>
            <h4 style="text-align: center; color: red"> <?php echo $error ?> </h4>
        <?php } ?>


        <!-- Создаем форму для добавления клиента -->
        <form name="addIncomes" method="POST">
            <div class="form-group">
                <label>Текст:</label>
                <textarea name="text" class="form-control" id="text"
                          placeholder="Текст"><?php if (isset($_POST['text'])) echo $_POST['text'] ?></textarea>
            </div>

            <div class="form-group">
                <label>Сумма:</label>
                <input name="sum" type="text" class="form-control" id="sum"
                       value="<?php if (isset($_POST['sum'])) echo $_POST['sum'] ?>" placeholder="Сумма">
            </div>

            <button type="submit" class="btn btn-success">Добавить приход</button>
        </form>
    </div>


</div>


</body>
</html>