<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>

<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-6">

        <!-- Если были заполнены не все поля говорим об этом -->
        <?php if (isset($error)) { ?>
            <h4 style="text-align: center; color: red"> <?php echo $error ?> </h4>
        <?php } ?>

        <!-- Если операция была успешной сообщаем -->
        <?php if (isset($success)) { ?>
            <h4 style="text-align: center; color: green"> <?php echo $success ?> </h4>
        <?php } ?>

        <!-- Если клиент указан правильно, создаем форму для добавления клиента -->
        <?php if (isset($comment)) { ?>

            <form name="changeClientComment" method="POST">

                <input name="id" style="display: none" type="text" class="form-control" id="id"
                       value="<?php echo $comment['id'] ?>">

                <div class="form-group">
                    <label>Сумма:</label>

                    <input class="form-control" type="text" name="amount" id="amount"
                           value="<?php echo $comment['amount'] ?>">
                </div>

                <div class="form-group">
                    <label>Комментарий:</label>
                <textarea name="comment" type="text" class="form-control" id="comment"
                          placeholder="Комментарий"><?php echo $comment['comment'] ?></textarea>
                </div>

                <button type="submit" id="save_comment" class="btn btn-success">Изменить заявку</button>
            </form>


            <script type="text/javascript">
                <?php
                $prepayment = $setup["prepayment"];
                $totalSum = $comment["totalSum"];
                echo "var prepayment = $prepayment \r\n;";
                echo "var totalSum = $totalSum; \r\n"

                ?>

                $(document).ready(function () {
                    $('#amount').on('change', function () {
                        price = $('#amount').val();

                        if (price < totalSum * prepayment) {
                            $('#price_error').remove();
                            $('#amount').closest('div').append(
                                '<p id="price_error"  style="text-align: center; color: red;;">' +
                                'Цена продажи не может быть минимальной цены</p>');

                            $('#save_comment').attr('disabled', 'disabled');
                        }else {
                            $('#price_error').remove();
                            $('#save_comment').attr('disabled', null);
                        }
                    })
                })
            </script>

        <?php } ?>

    </div>

</div>


</body>
</html>