<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>


<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">

        <!-- Если товаров не было найдено говорим об этом -->
        <?php if (isset($emptyResult)) { ?>
            <h3 style="text-align: center; color: red"><?php echo $emptyResult ?></h3>
        <?php } ?>

        <?php if (!empty($clients)) { ?>

            <h4 style="text-align: center">Клиенты</h4>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Телефон</th>
                    <th>Заявка</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($clients as $client) { ?>
                    <tr>
                        <td><?php echo $client['id'] ?></td>
                        <td><?php echo $client['name'] ?></td>
                        <td><?php echo $client['family'] ?></td>
                        <td><?php echo $client['phone'] ?></td>
                        <td style="width: 10%"><a href="addClientComment.php?client=<?php echo $client['id'] ?>">
                                <button type="button" class="btn btn-success">Добавить</button>
                            </a>
                        </td>
                    </tr>
                    <?php $comments = $client['comments'] ?>
                    <?php if (!empty($comments)) { ?>
                        <td colspan="5">
                            <?php if (isset($comments) && !empty($comments)) { ?>
                                <h4 style="text-align: center">Заявки</h4>
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Заявка</th>
                                        <th>Статус</th>
                                        <th>Дата создания</th>
                                        <th>Сумма оплаты</th>
                                        <th>Сумма по заказу</th>
                                        <th>Действие</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($comments as $comment) { ?>
                                        <tr class="success">
                                            <td style="width: 10%"><?php echo $comment['id'] ?></td>
                                            <td style="width: 80%"><?php echo $comment['comment'] ?></td>
                                            <td>
                                                <?php if($comment['status_key'] != 'issued'){ ?>
                                                <a href="#"
                                                   data-name="claim_status"
                                                   data-type="select" data-pk="<?php echo $comment['id'] ?>"
                                                   data-value="" data-source="/clients/getClaimStatus.php"
                                                   data-url="/clients/changeClaimStatus.php"
                                                   data-title="Сменить статус" class="product_status editable editable-click" data-original-title=""
                                                   title=""><?php echo $comment['status_name'] ?></a>
                                    <?php } else { echo $comment['status_name']; }?>
                                            </td>
                                            <td style="width: 80%"><?php echo $comment['createdAt'] ?></td>
                                            <td style="width: 10%;text-align: center; vertical-align: middle"><?php echo intval($comment['amount']) ?></td>
                                            <td style="width: 10%;text-align: center; vertical-align: middle"><span id="totalSum_<?php echo $comment['id'] ?>"><?php echo number_format($comment['totalSum'], 2) ?></span></td>
                                            <td>
                                                <?php if($comment['status_key'] != 'issued'){ ?>
                                                    <a  href="addProductToClient.php?client=
                                                    <?php echo $client['id'] . '&comment=' . $comment['id'] ?>">
                                                        <i class="fa fa-plus-square fa-2x"></i></a>

                                                    <a href="changeComment.php?comment=
                                                    <?php echo $comment['id'] ?>">
                                                        <i class="fa fa-edit fa-2x"></i></a>
                                                <?php }?>


                                                <a target="_blank" href="printComment.php?comment=
                                                    <?php echo $comment['id'] ?>">
                                                    <i class="fa fa-print fa-2x"></i></a>
                                                <a target="_blank" href="sendSmsToClient.php?client=
                                                    <?php echo $client['id'] ?>">
                                                    <i class="fa fa-mobile fa-2x"></i></a>
                                            </td>
                                        </tr>
                                        <?php $products = $comment['products'] ?>


                                        <?php if (!empty($products)) { ?>
                                            <tr>
                                                <td colspan="7">
                                                    <h4 style="text-align: center">Товары</h4>
                                                    <table class="table table-striped">
                                                        <thead>
                                                        <tr>
                                                            <th>ID</th>
                                                            <th>Артикул</th>
                                                            <th>Бренд</th>
                                                            <th>Наименование</th>
                                                            <th>Статус</th>
                                                            <th>Дата прихода</th>
                                                            <th>Цена закупки</th>
                                                            <th>Цена продажи</th>
                                                            <th>Количество</th>
                                                            <th>Поставщик</th>
                                                            <th>Действие</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <?php foreach ($products as $product) { ?>
                                                            <tr>
                                                                <td><?php echo $product['id'] ?></td>
                                                                <td><?php echo $product['artical'] ?></td>
                                                                <td><?php echo $product['brand'] ?></td>
                                                                <td><?php echo $product['name'] ?></td>
                                                                <td>
                                                                    <a href="#"
                                                                       data-name="product_status"
                                                                       data-type="select" data-pk="<?php echo $product['id'] ?>"
                                                                       data-value="" data-source="/products/getProductStatus.php"
                                                                       data-url="/products/changeProductStatus.php"
                                                                       data-title="Сменить статус" class="product_status editable editable-click" data-original-title=""
                                                                       title=""><?php echo $product['status_name'] ?></a>
                                                                </td>
                                                                <td><?php echo $product['delivery_time'] ?></td>
                                                                <td><?php echo $product['price'] ?></td>
                                                                <td><?php echo $product['price_sell'] ?></td>
                                                                <td><?php echo $product['count_product'] ?></td>
                                                                <td><?php echo $product['provider'] ?></td>
                                                                <td>
                                                                    <a href="deleteProductForClient.php?product=<?php echo $product['id'] . '&comment=' . $comment['id']?>">
                                                                        <button class="btn btn-danger">Удалить</button>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        <?php } ?>
                                                        </tbody>
                                                    </table>
                                                </td>

                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            <?php } ?>
                        </td>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        <?php } ?>

    </div>


</div>

<script>
    $('.product_status').editable({
        success: function(data) {
            data = JSON.parse(data);
            var comment = data.comment;
            var totalSum = data.totalSum;
            $('#totalSum_' + comment).text(totalSum)
        }
    });
</script>

</body>
</html>