<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>


<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">

        <!-- Если товаров не было найдено говорим об этом -->
        <?php if (isset($emptyResult)) { ?>
            <h3 style="text-align: center; color: red"><?php echo $emptyResult ?></h3>
        <?php } ?>

        <?php if (!empty($consignments)) { ?>

            <h4 style="text-align: center">Накладные</h4>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Номер</th>
                    <th>Дата</th>
                    <th>Сумма</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($consignments as $consignment) { ?>
                    <tr class="success">
                    <td><?php echo $consignment['id'] ?></td>
                    <td><?php echo $consignment['number'] ?></td>
                    <td><?php echo $consignment['date'] ?></td>
                    <td><?php echo $consignment['amount'] ?></td>


                    <?php $products = $consignment['products'] ?>
                    <?php if (!empty($products)) { ?>
                        <tr>
                            <td colspan="4">


                            <h4 style="text-align: center">Товары к накладной</h4>
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Артикул</th>
                                    <th>Бренд</th>
                                    <th>Статус</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Поставщик</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($products as $product) { ?>
                                    <tr>
                                        <td><?php echo $product['id'] ?></td>
                                        <td><?php echo $product['artical'] ?></td>
                                        <td><?php echo $product['brand'] ?></td>
                                        <td><?php echo $product['status_name'] ?></td>
                                        <td><?php echo $product['price'] ?></td>
                                        <td><?php echo $product['count_product'] ?></td>
                                        <td><?php echo $product['provider'] ?></td>
                                    </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tr>
                </tbody>
            </table>
        <?php } ?>

    </div>


</div>

</body>
</html>