
<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>

<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">
        <!-- Если были заполнены не все поля говорим об этом -->
        <?php if (isset($success)) { ?>
            <h4 style="text-align: center; color: green"> <?php echo $success ?> </h4>
        <?php } ?>

        <!-- Если были заполнены не все поля говорим об этом -->
        <?php if (isset($error)) { ?>
            <h4 style="text-align: center; color: red"> <?php echo $error ?> </h4>
        <?php } ?>
        <!-- Создаем форму для создания накладной -->
        <form name="create_consignment" method="POST">
            <div class="form-group">
                <label>Номер накладной:</label>
                <input name="number" type="text" class="form-control" id="number"
                       value="<?php if (isset($_POST['number'])) echo $_POST['number'] ?>"
                       placeholder="Номер накладной">
            </div>

            <div class="form-group">
                <label>Дата накладной:</label>
                <input name="date" type="text" class="form-control" id="date"
                       value="<?php if (isset($_POST['date'])) echo $_POST['date'] ?>" placeholder="2017-01-01">
            </div>

            <div class="form-group">
                <label>Сумма оплаты:</label>
                <input name="amount" type="text" class="form-control" id="amount"
                       value="<?php if (isset($_POST['amount'])) echo $_POST['amount'] ?>" placeholder="Сумма оплаты">
            </div>

            <?php if (!empty($currentProducts)) { ?>

                <h4 style="text-align: center">Товары для накладной</h4>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Артикул</th>
                        <th>Бренд</th>
                        <th>Цена</th>
                        <th>Количество</th>
                        <th>Поставщик</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($currentProducts as $currentProduct) { ?>
                        <tr>
                            <td><?php echo $currentProduct['id'] ?></td>
                            <td><?php echo $currentProduct['artical'] ?></td>
                            <td><?php echo $currentProduct['brand'] ?></td>
                            <td><?php echo $currentProduct['price'] ?></td>
                            <td><?php echo $currentProduct['count_product'] ?></td>
                            <td><?php echo $currentProduct['provider'] ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <h3 style="text-align: center;color: red">Товаров не выбрано</h3>
            <?php } ?>

            <button style="float: right" type="submit"
                <?php if (empty($currentProduct)) { ?>
                    disabled="disabled"
                <?php } ?>
                    class="btn btn-success">Создать</button>
        </form>

        <a href="addGroupProduct.php">
            <button style="float: left" type="button" class="btn btn-success">Добавить товары в список</button>
        </a>


    </div>
</div>

</body>
</html>