<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>


<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">

        <!-- Если товаров не было найдено говорим об этом -->
        <?php if (isset($emptyResult)) { ?>
            <h3 style="text-align: center; color: red"><?php echo $emptyResult ?></h3>
        <?php } ?>

        <?php if (!empty($products)) { ?>

            <h4 style="text-align: center">Уже добавленные товары ранее</h4>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Артикул</th>
                    <th>Бренд</th>
                    <th>Наименование</th>
                    <th>Статус</th>
                    <th>Дата прихода</th>
                    <th>Цена закупки</th>
                    <th>Цена продажи</th>
                    <th>Количество</th>
                    <th>Поставщик</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($products as $product) { ?>
                    <tr>
                        <td><?php echo $product['id'] ?></td>
                        <td><?php echo $product['artical'] ?></td>
                        <td><?php echo $product['brand'] ?></td>
                        <td><?php echo $product['name'] ?></td>
                        <td><?php echo $product['status_name'] ?></td>
                        <td><?php echo $product['delivery_time'] ?></td>
                        <td><?php echo $product['price'] ?></td>
                        <td><?php echo $product['price_sell'] ?></td>
                        <td><?php echo $product['count_product'] ?></td>
                        <td><?php echo $product['provider'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        <?php } ?>

    </div>


</div>



</body>
</html>