<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>


<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">

        <!-- Если товаров не было найдено говорим об этом -->
        <?php if (isset($emptyResult)) { ?>
            <h3 style="text-align: center; color: red"><?php echo $emptyResult ?></h3>
        <?php } ?>

        <?php if (!empty($products)) { ?>

            <h4 style="text-align: center">Уже добавленные товары ранее</h4>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Артикул</th>
                    <th>Бренд</th>
                    <th>Статус</th>
                    <th>Цена закупки</th>
                    <th>Цена продажи</th>
                    <th>Количество</th>
                    <th>Поставщик</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($products as $product) { ?>
                    <tr>
                        <td><?php echo $product['id'] ?></td>
                        <td><?php echo $product['artical'] ?></td>
                        <td><?php echo $product['brand'] ?></td>
                        <td><a href="#" class="product_status"><?php echo $product['status_name'] ?></a></td>
                        <td><?php echo $product['price'] ?></td>
                        <td><?php echo $product['price_sell'] ?></td>
                        <td><?php echo $product['count_product'] ?></td>
                        <td><?php echo $product['provider'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        <?php } ?>

    </div>


</div>


<link rel="stylesheet" href="/resource/select2.min.css">
<script type="text/javascript" src="/resource/select2.min.js"></script>
<script type="text/javascript">
    $(".product_status").on('click', function(){
        $(".product_status").select2({
            minimumInputLength: 0,
            ajax: {
                url: "getProductStatus.php",
                dataType: 'json',
                type: "GET",
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.name,
                                slug: item.key,
                                id: item.id
                            }
                        })
                    };
                }
            }
        });
    })
</script>

</body>
</html>