
<!-- Подключаем наш навбар -->
<?php include "../header.phtml" ?>

<script>
    bkLib.onDomLoaded(function()
    {
        new nicEditor().panelInstance('NicEdit');
    });
</script>

<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-6">

        <!-- если возникла ошибка или вставка не удалась -->

        <?php if (isset($error)) { ?>
            <h3 style="text-align: center; color: red"><?php echo $error ?></h3>
        <?php } ?>
        <?php if (isset($success)) { ?>
            <h3 style="text-align: center; color: green"><?php echo $success ?></h3>
        <?php } ?>

        <!-- Создаем форму для добавления товаров -->
        <form name="changeSetup" method="POST">
            <div class="form-group">
                <label>Юр. лицо:</label>
                <input name="face" type="text" class="form-control" id="face"
                       value="<?php if(isset($setup['face'])) echo $setup['face'] ?>" placeholder="Юр. лицо">
            </div>

            <div class="form-group">
                <label>Адрес:</label>
                <input name="address" type="text" class="form-control" id="address"
                       value="<?php if(isset($setup['address'])) echo $setup['address'] ?>" placeholder="Адрес">
            </div>

            <div class="form-group">
                <label>Цена продажи(коф.):</label>
                <input name="price_sell" type="text" class="form-control" id="price_sell"
                       value="<?php if(isset($setup['price_sell'])) echo $setup['price_sell'] ?>" placeholder="Цена продажи">
            </div>
            <div class="form-group">
                <label>Минимальная цена(коф.):</label>
                <input name="min_price" type="text" class="form-control" id="min_price"
                       value="<?php if(isset($setup['min_price'])) echo $setup['min_price'] ?>" placeholder="Минильная цена">
            </div>

            <div class="form-group">
                <label>Процент предоплаты(коф. (0-1)):</label>
                <input name="prepayment" type="text" class="form-control" id="prepayment"
                       value="<?php if(isset($setup['prepayment'])) echo $setup['prepayment'] ?>" placeholder="Процент предоплаты">
            </div>

            <div class="form-group">
                <label>Текст для печатной формы:</label>

                <textarea name="text" id="NicEdit" cols="110" rows="20">
                    <?php if(isset($setup['text'])) echo $setup['text'] ?>
                </textarea>

            </div>


            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    </div>

</div>

</body>
</html>